---
title: "Pokemon_Usage_OverTime"
author: "Daven Lagu"
date: "2025-02-19"
output: pdf_document
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(jsonlite)
library(purrr)
```

```{r}
json_url_list <- c("https://www.smogon.com/stats/2022-11/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2022-12/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-01/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-02/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-03/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-04/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-05/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-06/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-07/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-08/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-09/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-10/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-11/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2023-12/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-01/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-02/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-03/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-04/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-05/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-06/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-07/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-08/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-09/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-10/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-11/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2024-12/chaos/gen9ou-1695.json",
                   "https://www.smogon.com/stats/2025-01/chaos/gen9ou-1695.json")

```

```{r}
# Initialize empty list to append data
all_data <- list()

# Loop through all urls to get Pokemon names, usages, and dates
for (i in seq_along(json_url_list)) {
  
  # Get data for each json url in list
  json_url <- json_url_list[i]
  json_data <- fromJSON(json_url_list[i])
  # Extract pokemon data from json data type
  pkmn_data <- json_data$data
  # Initialize empty list to append values
  result_list <- list()
  # Extract date from url string
  date_value <- str_extract(json_url, "\\d{4}-\\d{2}")
  
  # Loop through each Pokémon data and extract the relevant information
  for (pokemon_name in names(pkmn_data)) {
    pokemon_info <- pkmn_data[[pokemon_name]]
    usage <- pokemon_info$usage
    
    result_list[[pokemon_name]] <- data.frame(
      Pokemon = pokemon_name,
      Usage = usage,
      Date = date_value,
      stringsAsFactors = FALSE
    )
  }
  # Combine the list of data frames into one data frame
  all_data[[i]] <- bind_rows(result_list)
}

# Combine the list of all data into single data frame
pkmn_usage_ot_data <- bind_rows(all_data)
  
# Print the pokemon usage over time data frame for all data in time frame
pkmn_usage_ot_data
```

```{r}
# Create list of all unique dates
dates <- unique(pkmn_usage_ot_data$Date)
# Get names of current top 10 gen 9 OU pokemon by usage
pkmn_recent_top_usage_names <- pkmn_usage_ot_data %>% filter(Date == tail(dates, 1)) %>% arrange(desc(Usage)) %>% head(10) %>% pull(Pokemon)

# Print names of top 10 most used gen 9 pokemon in OU tier 
print(pkmn_recent_top_usage_names)

# Create data frame filtered to only top 10 most used and format Date/Pokemon data types 
pkmn_top10 <- pkmn_usage_ot_data %>%
  filter(Pokemon %in% pkmn_recent_top_usage_names) %>%
  mutate(Date = as.Date(paste0(Date, "-01"), format = "%Y-%m-%d"),
         Pokemon = as.factor(Pokemon))

# Create line plot showing Top 10 Gen 9 OU Pokemon usage over time
ggplot(pkmn_top10, aes(x = Date, y = Usage, color = Pokemon, group = Pokemon)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(title = "Gen 9 OU Pokémon Usage Over Time",
       x = "Date",
       y = "Usage",
       color = "Pokémon")
```

